---
- name: this play book install the httpd RHEL OS  packages and apche2 on ubuntu and start the service.
  hosts: all
  become: true
  vars:
    port: 8082
  tasks:
  - name: install the httpd packages
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start the httpd service  

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  - name: copy index.html file to all the servers
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  - name: Ensure the default httpd port is 8082 on RedHat
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}        
    when: ansible_os_family == "RedHat"
    notify: restart httpd

  - name: Ensure the default httpd port is 8082 on Ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache2        

  handlers:
  - name: start the httpd service
    service:
      name: httpd
      state: started
        #when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
        #when: ansible_os_family == "Debian"

  - name: restart httpd
    service:
      name: httpd
      state: restarted
        #when: ansible_os_family == "Redhat"

  - name: restart apache2
    service:
      name: apache2
      state: restarted
        # when: ansible_os_family == "Debian"      
