---
- name: this play book install the httpd packages and start the service
  hosts: webservers-rhel
  become: true
  tasks:
  - name: install the httpd packages
    yum:
      name: httpd
      state: installed   
  - name: start the httpd service
    service:
      name: httpd
      state: started    
