---
- name: this play book install the httpd RHEL OS  packages and apche2 on ubuntu and start the service.
  hosts: all
  become: true
  tasks:
  - name: install the httpd packages
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"  
  - name: start the httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
