---
# tasks file for setup-httpd
  - name: install the httpd packages
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start the httpd service

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  - name: copy index.html file to all the servers
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
  - name: Ensure the default httpd port is 8082 on RedHat
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart httpd

  - name: Ensure the default httpd port is 8082 on Ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache2        
