---
# handlers file for setup-httpd
  - name: start the httpd service
    service:
      name: httpd
      state: started
        #when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
        #when: ansible_os_family == "Debian"

  - name: restart httpd
    service:
      name: httpd
      state: restarted
        #when: ansible_os_family == "Redhat"

  - name: restart apache2
    service:
      name: apache2
      state: restarted
        # when: ansible_os_family == "Debian"
